
/*
 * Ioctl definitions
 */

#define USBCAM_IOC_MAGIC  'U'

#define USBCAM_IOCTL_STREAMON         _IO(USBCAM_IOC_MAGIC, 30)
#define USBCAM_IOCTL_STREAMOFF        _IO(USBCAM_IOC_MAGIC, 40)
#define USBCAM_IOCTL_GRAB             _IO(USBCAM_IOC_MAGIC, 50)
#define USBCAM_IOCTL_PANTILT          _IOW(USBCAM_IOC_MAGIC, 60, int)
#define USBCAM_IOCTL_PANTILT_RESET    _IO(USBCAM_IOC_MAGIC, 70)

#define USBCAM_IOC_MAXNR 5
